// src/components/about/content-card.tsx
import type { ProfileItem } from '@/lib/types';
import { downloadFile } from '@/lib/utils';

interface ContentCardProps {
  data: ProfileItem;
  applyMarginTop?: boolean;
  nested?: boolean;
}

export function ContentCard({ data, applyMarginTop, nested }: ContentCardProps) {
  return (
    <div className={`p-0 m-0 ${nested ? 'text-black text-[80%]' : 'text-inherit'} ${applyMarginTop ? 'mt-[10px]' : ''}`}>
      {data.link && data.title ? (
        <a href={data.link} target="_blank" rel="noopener noreferrer" className="text-[#039be5] no-underline transition-colors duration-300 ease-in-out hover:text-[#4fc3f7]">
          <b>{data.title}</b>
        </a>
      ) : data.title ? (
        <a className="text-inherit cursor-default pointer-events-none">
          <b>{data.title}</b>
        </a>
      ) : null}

      {data.title && data.position && <br />}

      {data.position && <b className={nested ? 'text-black' : undefined}>{data.position}</b>}

      {data.dates && <p className={`leading-[1.6] m-0 ${nested ? '!text-black' : 'text-white'}`}>{data.dates}</p>}

      {data.skills && <p className={`text-xs italic mt-0 leading-[1.6] m-0 ${nested ? '!text-black' : 'text-white'}`}>{data.skills}</p>}

      {data.description && (
        <p className={`text-xs mt-0 leading-[1.6] m-0 ${nested ? '!text-black' : 'text-white'}`} dangerouslySetInnerHTML={{ __html: data.description }} />
      )}

      {data.additionalContent && (
        <p className={`text-xs mt-0 leading-[1.6] m-0 ${nested ? '!text-black' : 'text-white'}`} dangerouslySetInnerHTML={{ __html: data.additionalContent }} />
      )}

      {data.downloadLink && (
        <button type="button" onClick={() => downloadFile(data.downloadLink!, data.downloadFilename!)} className="text-[#039be5] no-underline transition-colors duration-300 ease-in-out hover:text-[#4fc3f7] bg-transparent border-none cursor-pointer p-0 text-sm font-inherit">
          {data.downloadLabel}
        </button>
      )}

      {data.expandedContent && (
        <div className="content bg-[#f1f1f1] text-black p-1.5 rounded-md">
          <p className="text-xs mt-0" dangerouslySetInnerHTML={{ __html: data.expandedContent }} />
        </div>
      )}
    </div>
  );
}

// src/app/components/about/content-card.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';

export interface ProfileItem {
  title?: string;
  link?: string;
  dates?: string;
  position?: string;
  skills?: string;
  description?: string;
  expandedContent?: string;
  additionalContent?: string;
  downloadLink?: string;
  downloadLabel?: string;
  downloadFilename?: string;
}

@Component({
  selector: 'content-card',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="section text-inherit" [class.margin-top]="applyMarginTop">
      <a *ngIf="data.link && data.title" [href]="data.link" target="_blank">
        <b>{{ data.title }}</b>
      </a>
      <a *ngIf="!data.link && data.title" class="text-inherit cursor-default pointer-events-none hover:text-inherit hover:transform-none">
        <b>{{ data.title }}</b>
      </a>
      <br *ngIf="data.title && data.position">
      <b *ngIf="data.title && data.position">{{ data.position }}</b>
      <b *ngIf="!data.title && data.position">{{ data.position }}</b>

      <p *ngIf="data.dates">{{ data.dates }}</p>

      <p *ngIf="data.skills" class="text-xs italic mt-1.5">
        {{ data.skills }}
      </p>

      <p *ngIf="data.description" class="text-xs mt-1.5" [innerHTML]="data.description"></p>

      <p *ngIf="data.additionalContent" class="text-xs mt-1.5" [innerHTML]="data.additionalContent"></p>

      <a *ngIf="data.downloadLink"
         [href]="data.downloadLink"
         [download]="data.downloadFilename"
         class="text-[#039be5]">
        {{ data.downloadLabel }}
      </a>
    </div>
  `,
  styles: [`
    :host-context(.content) .section {
      color: black;
      font-size: 80%;
    }

    :host-context(.content) p {
      color: black;
    }

    :host-context(.content) b {
      color: black;
    }

    :host-context(.content) a {
      color: #039be5;
    }
  `]
})
export class ContentCardComponent {
  @Input() data!: ProfileItem;
  @Input() applyMarginTop = false;
}
