// src/components/about/education-section.tsx
'use client';

import { useState } from 'react';
import type { Certification, EducationInfo, ProfileItem } from '@/lib/types';
import { ContentCard } from './content-card';

interface EducationSectionProps {
  education: EducationInfo;
  projects: Record<string, ProfileItem>;
  certifications: Certification[];
}

export function EducationSection({ education, projects, certifications }: EducationSectionProps) {
  const [count, setCount] = useState(0);
  const display = count > 0;

  const toggle = (expand: boolean) => {
    if (expand) {
      setCount((prev) => prev + 1);
    } else {
      setCount(0);
    }
  };

  return (
    <>
      <h2 id="education" className="text-[2em] mt-[30px] mb-0 text-white [text-shadow:0_0_5px_rgba(3,155,229,0.3)] hover:[text-shadow:0_0_10px_rgba(3,155,229,0.6)] transition-[text-shadow] duration-300 ease-in-out leading-[1.3]">
        Education
      </h2>
      <div className="p-0 m-0 text-inherit">
        <b>{education.institution}</b>
        <p className="leading-[1.6] m-0 text-white">{education.dates}</p>
        <p className="leading-[1.6] m-0 text-white">{education.degree}</p>

        {display && certifications.length > 0 && (
          <div className="mt-2">
            {certifications.map((cert) => (
              <p key={cert.name} className="leading-[1.6] m-0 text-white text-xs">
                {cert.name} ({cert.year})
              </p>
            ))}
          </div>
        )}

        <div id="more-education" className="mt-1.5">
          {display && (
            <div className="content bg-[#f1f1f1] text-black p-1.5 rounded-md">
              {count >= 1 && <ContentCard data={projects['archr']} nested />}
              {count >= 1 && <ContentCard data={projects['solar']} applyMarginTop nested />}
              {count === 2 && <ContentCard data={projects['dome']} applyMarginTop nested />}
            </div>
          )}

          {count < 2 ? (
            <button
              type="button"
              className="bg-[#eee] text-[#444] cursor-pointer border border-white text-left text-[9px] rounded-[5px] lowercase py-px px-1.5 mt-[5px] hover:bg-[#ccc]"
              onClick={() => toggle(true)}
            >
              more
            </button>
          ) : (
            <button
              type="button"
              className="bg-[#eee] text-[#444] cursor-pointer border border-white text-left text-[9px] rounded-[5px] lowercase py-px px-1.5 mt-[5px] hover:bg-[#ccc]"
              onClick={() => toggle(false)}
            >
              less
            </button>
          )}
        </div>
      </div>
    </>
  );
}

// src/app/components/about/education-section.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Store } from '@ngrx/store';
import { Observable } from 'rxjs';
import { ContentCardComponent } from './content-card.component';
import { fadeIn, slideInLeft } from '../../animations/animations';
import { ExpandableSection, EducationInfo, ProfileItem } from '../../models/models';
import { selectEducation, selectEducationProjects } from '../../store/app.selectors';

@Component({
  selector: 'education-section',
  standalone: true,
  imports: [CommonModule, ContentCardComponent],
  animations: [fadeIn, slideInLeft],
  template: `
    <h2 class="margin-top-60" @slideInLeft>Education</h2>
    <div class="section">
      <b>{{ (education$ | async)?.institution }}</b>
      <p>{{ (education$ | async)?.dates }}</p>
      <p>{{ (education$ | async)?.degree }}</p>

      <div id="more-education">
        <div *ngIf="section.display" class="content" @fadeIn>
          <content-card *ngIf="section.count >= 1 && (projects$ | async)" [data]="(projects$ | async)!['archr']"></content-card>
          <content-card *ngIf="section.count >= 1 && (projects$ | async)" [data]="(projects$ | async)!['solar']" [applyMarginTop]="true"></content-card>
          <content-card *ngIf="section.count === 2 && (projects$ | async)" [data]="(projects$ | async)!['dome']" [applyMarginTop]="true"></content-card>
        </div>

        <button *ngIf="section.count < 2" type="button" class="collapsible" (click)="toggle(true)">more</button>
        <button *ngIf="section.count === 2" type="button" class="collapsible" (click)="toggle(false)">less</button>
      </div>
    </div>
  `,
  styles: [`
    .section {
      color: inherit;
    }

    .collapsible {
      background-color: #eee;
      color: #444;
      cursor: pointer;
      border: none;
      text-align: left;
      font-size: 9px;
      border: 1px solid white;
      border-radius: 5px;
      text-transform: lowercase;
      padding: 1px 6px;
      margin-top: 5px;
    }

    .active,
    .collapsible:hover {
      background-color: #ccc;
    }

    .content {
      background-color: #f1f1f1;
      color: black;
      padding: 6px;
      border-radius: 6px;
    }

    .content .section {
      color: black;
      font-size: 80%;
    }

    .content p {
      color: black;
    }

    .content b {
      color: black;
    }

    .content a {
      color: #039be5;
    }
  `]
})
export class EducationSectionComponent {
  education$: Observable<EducationInfo | undefined>;
  projects$: Observable<Record<string, ProfileItem> | undefined>;

  section: ExpandableSection = { display: false, count: 0 };

  constructor(private store: Store) {
    this.education$ = this.store.select(selectEducation);
    this.projects$ = this.store.select(selectEducationProjects);
  }

  toggle(expand: boolean): void {
    this.section.display = expand;
    if (expand) {
      this.section.count += 1;
    } else {
      this.section.count = 0;
    }
  }
}
