// src/components/about/extracurriculars-section.tsx
'use client';

import { useState } from 'react';
import type { ProfileItem, PublishedWork } from '@/lib/types';
import { ContentCard } from './content-card';

interface ExtracurricularsSectionProps {
  activities: Record<string, ProfileItem>;
  publishedWorks: PublishedWork[];
}

export function ExtracurricularsSection({ activities, publishedWorks }: ExtracurricularsSectionProps) {
  const [count, setCount] = useState(0);
  const display = count > 0;

  const toggle = (expand: boolean) => {
    if (expand) {
      setCount((prev) => prev + 1);
    } else {
      setCount(0);
    }
  };

  return (
    <>
      <h2 className="text-[2em] mt-[30px] mb-0 text-white [text-shadow:0_0_5px_rgba(3,155,229,0.3)] hover:[text-shadow:0_0_10px_rgba(3,155,229,0.6)] transition-[text-shadow] duration-300 ease-in-out leading-[1.3]">
        Extracurriculars
      </h2>
      <ContentCard data={activities['teaching']} applyMarginTop />

      <div id="more-extracurriculars">
        {display && (
          <div>
            {count >= 1 && <ContentCard data={activities['volunteering']} applyMarginTop />}
            {count >= 1 && <ContentCard data={activities['travel']} applyMarginTop />}
            {count === 2 && <ContentCard data={activities['jung']} applyMarginTop />}

            {count === 2 && (
              <div className="p-0 m-0 text-inherit mt-[10px]">
                <b>Published Works</b>
                {publishedWorks.map((work, i) => (
                  <p key={i} className="text-sm leading-[1.6] m-0 text-white">
                    &#x2022;{' '}
                    <a href={work.downloadPath} download={work.downloadFilename} className="text-[#039be5] no-underline transition-colors duration-300 ease-in-out hover:text-[#4fc3f7]">
                      {work.title}
                    </a>
                  </p>
                ))}
              </div>
            )}
          </div>
        )}

        {count < 2 ? (
          <button
            type="button"
            className="bg-[#eee] text-[#444] cursor-pointer border border-white text-left text-[9px] rounded-[5px] lowercase py-px px-1.5 mt-[5px] hover:bg-[#ccc]"
            onClick={() => toggle(true)}
          >
            more
          </button>
        ) : (
          <button
            type="button"
            className="bg-[#eee] text-[#444] cursor-pointer border border-white text-left text-[9px] rounded-[5px] lowercase py-px px-1.5 mt-[5px] hover:bg-[#ccc]"
            onClick={() => toggle(false)}
          >
            less
          </button>
        )}
      </div>
    </>
  );
}

// src/app/components/about/extracurriculars-section.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ContentCardComponent } from './content-card.component';
import { fadeIn, slideInLeft } from '../../animations/animations';
import { ExpandableSection } from './about.constants';
import { ACTIVITIES, PUBLISHED_WORKS } from './about.constants';

@Component({
  selector: 'extracurriculars-section',
  standalone: true,
  imports: [CommonModule, ContentCardComponent],
  animations: [fadeIn, slideInLeft],
  template: `
    <h2 @slideInLeft>Extracurriculars</h2>
    <content-card [data]="activities['teaching']" [applyMarginTop]="true"></content-card>

    <div id="more-ec">
      <div *ngIf="section.display" @fadeIn>
        <content-card *ngIf="section.count >= 1" [data]="activities['volunteering']" [applyMarginTop]="true"></content-card>
        <content-card *ngIf="section.count >= 1" [data]="activities['travel']" [applyMarginTop]="true"></content-card>
        <content-card *ngIf="section.count === 2" [data]="activities['jung']" [applyMarginTop]="true"></content-card>

        <div *ngIf="section.count === 2" class="section margin-top">
          <b>Published Works</b>
          <p *ngFor="let work of publishedWorks" style="font-size: 14px;">
            &#x2022; <a [href]="work.downloadPath" [download]="work.downloadFilename" style="color: #039be5;">{{ work.title }}</a>
          </p>
        </div>
      </div>

      <button *ngIf="section.count < 2" type="button" class="collapsible" (click)="toggle(true)">more</button>
      <button *ngIf="section.count === 2" type="button" class="collapsible" (click)="toggle(false)">less</button>
    </div>
  `,
  styles: [`
    .collapsible {
      background-color: #eee;
      color: #444;
      cursor: pointer;
      border: none;
      text-align: left;
      font-size: 9px;
      border: 1px solid white;
      border-radius: 5px;
      text-transform: lowercase;
      padding: 1px 6px;
      margin-top: 5px;
    }

    .active,
    .collapsible:hover {
      background-color: #ccc;
    }

    .section {
      color: inherit;
    }
  `]
})
export class ExtracurricularsSectionComponent {
  activities = ACTIVITIES;
  publishedWorks = PUBLISHED_WORKS;

  section: ExpandableSection = { display: false, count: 0 };

  toggle(expand: boolean): void {
    this.section.display = expand;
    if (expand) {
      this.section.count += 1;
    } else {
      this.section.count = 0;
    }
  }
}
